name: Close Snaps

on:
  pull_request:
    types: [closed]

jobs:
  close:
    runs-on: ubuntu-latest

    timeout-minutes: 5

    steps:
    - name: Install Snapcraft
      uses: samuelmeuli/action-snapcraft@v1
      with:
        snapcraft_token: ${{ secrets.SNAPCRAFT_TOKEN }}

    - name: Close obsolete channels
      run: |
        snapcraft close mir-core20 "edge/pr${{ github.event.number }}" || true
        for snap in mir-core20 mir-kiosk mir-test-tools egmde-confined-desktop; do
          snapcraft close "$snap" "edge/mir-pr${{ github.event.number }}" || true
        done
